spring.datasource.url=jdbc:sqlserver://localhost:14333;databaseName=ordersdb;encrypt=true;trustServerCertificate=true;loginTimeout=30
spring.datasource.username=sa
spring.datasource.password=EgitronTestBE#2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

server.port=8080
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG


# ===== SWAGGER ========
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ==== AUTHENTICATION IN PROGRESS....
security.jwt.secret=<YOUR-SECRET-KEY-HS256-32CHARS>
security.jwt.issuer=orders-system
security.jwt.exp-minutes=60

# Resource Server ->
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=


# ====== EMAIL VALIDATION API =====
external.email.base-url=https://api.captainverify.com
external.email.path=/v2/verify
external.email.api-key=<GENERATE-A-API-KEY-AT-CAPTAINVERIFY.COM>
external.email.timeout-ms=3000
#external.email.method=GET
external.email.enabled=true

# ====== EMAIL SENDER ======
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=<YOUR-EMAIL-ADRESS>
spring.mail.password=<EMAIL-APP-PASSWORD>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

pp.mail.from=<EMAIL-SENDER>

app.errorlog.report.recipient=<RECIPIENT-EMAIL>

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
