spring.datasource.url=jdbc:sqlserver://localhost:14333;databaseName=ordersdb;encrypt=true;trustServerCertificate=true;loginTimeout=30
spring.datasource.username=sa
spring.datasource.password=EgitronTestBE#2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

server.port=8080
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG


# ===== SWAGGER ========
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ==== AUTHENTICATION IN PROGRESS....
# Chave secreta HS256 (usa 32+ chars; em prod usa var de ambiente/Secret Manager)
security.jwt.secret=NHEuEK7h9sFI+grJ6YZ1oXzWDxITobCfFtASHIppJS0=
security.jwt.issuer=orders-system
security.jwt.exp-minutes=60

# Resource Server -> usaremos JwtDecoder com secret (ver SecurityConfig)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=


# ====== EMAIL VALIDATION API =====
external.email.base-url=https://api.captainverify.com
external.email.path=/v2/verify
external.email.api-key=bYRxnQWFidCmcq05VJiH6e73p40IN2Td
external.email.timeout-ms=3000
#external.email.method=GET
external.email.enabled=true

# ====== EMAIL SENDER ======
# SMTP (ex.: Gmail com App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=claudia.c.lamas@gmail.com
spring.mail.password=rvvqyfjothrijnvq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Remetente
app.mail.from=claudia.c.lamas@gmail.com

# Para quem enviar o relatório
app.errorlog.report.recipient=lamasclaudiadev@gmail.com

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
